### PR TITLE
Add simple typescript example with multiple routes

### PR DESCRIPTION
**Pull request by mwildehahn**
There was some confusion in this thread: https://spectrum.chat/zeit?thread=4e4b5f23-65b9-43bc-a67f-3de197b98c54 around how to get typescript to work. I thought adding a more complex example with multiple routes would be useful.

### CODE REVIEW

**Comment by rauchg** [comment]
That's amazing. I love TypeScript. I love Now. Thanks @mwildehahn

**Comment by mwildehahn** [comment]
This small example was definitely my 💡 moment with v2. Y'all are doing amazing things.

**Comment by kyledetella** [comment]
Thanks for this @mwildehahn! This is super helpful. I have been struggling for a while now with getting a TS server running on v2 (as per the spectrum thread above) and it feels good to be unblocked.

I did run into one issue though and I'm not sure if it warrants a mention here, but in my [test app](https://github.com/kyledetella/ts-on-now-2.0) (TS + express), I kept running into this error when invoking an endpoint:

```
module initialization error: TypeError
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:269:10)
    at Object.<anonymous> (/var/task/launcher.js:19:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

As it turns out, this was because I wasn't exporting anything from my `index.ts` file. Once I added an export it worked like a charm.

*before*

```javascript
import * as express from "express";

const { PORT = 3022 } = process.env;

const app = express();

app.get("/", (_, res) => {
  res.json({ data: `${Date.now()}` });
});

app.listen(PORT);
```

*after*

```javascript
import * as express from "express";

const { PORT = 3022 } = process.env;

const app = express();

app.get("/", (_, res) => {
  res.json({ data: `${Date.now()}` });
});

app.listen(PORT);

export default app;
```

I'm not sure if this is a requirement of the builder itself or the internals of the `now` runtime. Any thoughts on what the right layer to document (or add error handling) might be for this? I'd be happy to contribute to a PR.

**Comment by timothyis** [comment]
Hi @mwildehahn, I deployed this example but it's not seeming to do anything, is this expected? https://nodejs-koa-ts-9nh9khn0i.now.sh/

**Comment by mwildehahn** [comment]
Yea, it’s returning a 404 by default. If you POST to `/first` or `/second`
it should echo back the JSON

**Comment by timothyis** [comment]
@mwildehahn Do you think you could render something on the index route, for example linking to `first`? Then we could have something that POSTs to `/second` e.g. a form that posts something?

We generally try to make an example as easy as possible to get the grasp of from looking at them 🙏

**Comment by mwildehahn** [comment]
Pushed an update which includes more info that might be better in an
example.

**Comment by joecohens** [comment]
Thank you @mwildehahn!

**Pull request merged**
