### PR TITLE
feat: add umijs antd typescript demo

### PR DESCRIPTION
**Pull request by ycjcl868**
https://umi-v2.now.sh/

### CODE REVIEW

**Comment by timothyis** [comment]
Wow, thank you @ycjcl868!

Would you be up for turning this example into something a little more complex? The idea is that our examples can follow the static example (https://github.com/zeit/now-examples/tree/master/static) but in the style of the framework, as it is meant to be. Is that something you'd be interested in working on?

I can't wait to have a solid example of umijs and typescript merged in 😍

**Comment by ycjcl868** [comment]
@timothyis It's OK, I will give full play to the advantages of [antd](http://ant.design) and [umijs](https://umijs.org). Thank you!

**Comment by ycjcl868** [comment]
[umi-v2.now.sh](umi-v2.now.sh) is ok.

**Comment by ycjcl868** [comment]
Anything else?

**Comment by msweeneydev** [comment]
Hey @ycjcl868, just reviewing now, thank you so much for this!

**Comment by ycjcl868** [comment]
I merge master into the branch, just a minute.

**Comment by msweeneydev** [comment]
Thanks for contributing @ycjcl868 - great work!

**Comment by ycjcl868** [comment]
Thank you ~

**Pull request merged**
