### PR TITLE
nodejs-ts and typescript setup fixes

### PR DESCRIPTION
**Pull request by chibicode**
### `node-ts`

- Add missing `.gitignore` and `.nowignore`
- Add `typescript` to `package.json` - otherwise `ncc` builtin version (`3.2.2` as of now) is used
- Downgrade `@types/node` to 8.1.x because that's the node version used by `now` right now

### `typescript`

- Add `@types/node`
- Add `.gitignore`
- Use `now dev` instead of `nodemon` for the typescript example
- Upgrade `typescript` and remove `ts-node`
- Tested that `yarn dev` still works

### Both

- Add `yarn.lock` for both - not sure if this is needed, but I was looking at [zeit/og-image](https://github.com/zeit/og-image) as a reference, and it included `yarn.lock`

### CODE REVIEW

**Comment by TejasQ** [comment]
Hmmm @chibicode, it's red...

**Comment by chibicode** [comment]
@TejasQ I think the failing example is golang?

Screen Shot 2019-06-12 at 11 01 21 AM

**Comment by TejasQ** [comment]
You're right. I guess @igorklopov or @timothyis have an answer why...

**Comment by msweeneydev** [comment]
Hey @chibicode, thanks for submitting this pull request. As you might have seen, this example has been removed as we recently simplified the examples repository.

As a result, I am closing this pull request. Thank you again for contributing, we really appreciate you taking the time to do so.

**Pull request closed without merging**
