### PR TITLE
Added create-nuxt-app` now-build command

### PR DESCRIPTION
**Pull request by Developerayo**
Added `create-nuxt-app` now-build command @timothyis

### CODE REVIEW

**Comment by Developerayo** [comment]
@timothyis

**Comment by timothyis** [comment]
Thanks @Developerayo, I'll be reviewing this today.

**Comment by Developerayo** [comment]
@timothyis

**Comment by msweeneydev** [comment]
Hey @Developerayo, we recently added a Nuxt.js example along with a host of others that no longer require configuration, therefore I am closing this pull request. With the example added we are now looking to merge your guide pull request very shortly.

**Comment by Developerayo** [comment]
Oh great!
Thanks @manovotny looking forward to it!

**Pull request closed without merging**
