### PR TITLE
add ghost v2 example

### PR DESCRIPTION
**Pull request by antony**
I've added a ghost v2 example in its absence.
It's based roughly on the [original v1 example](https://github.com/now-examples/ghost).
I don't think it would be difficult to make this zeit v2 compatible, but I simply don't know how I'm afraid.

This repo has two significant differences from the original (aside from being v2 not v1), those are to make ghost more useful on an ephemeral filesystem (end users aren't likely going to be the same users who can manage git and now deployments!):

1. Added GCP storage adapter to store assets on Google Cloud Platform
2. Added external MySQL database connectivity

It's important to note that due to a [bug in ghost](https://github.com/TryGhost/Ghost/issues/8795) with `contentPath`, when using it as a node module, it's quite difficult to get a local sqlite database to be writable anyway.

### CODE REVIEW

**Comment by antony** [comment]
Meant to mention, this should fix #50 and #155

**Comment by TooTallNate** [comment]
You seem to have pushed a git submodule reference 🤔

**Comment by antony** [comment]
@TooTallNate whoops! I based this on my working deployment and thought I'd cleared it out. I'll fix.

**Comment by antony** [comment]
@TooTallNate Okay - this time you get the source :man_facepalming:

**Comment by timothyis** [comment]
Hi @antony, apologies for the delayed response to your PR, we appreciate the effort that went into it!

Unfortunately, we are not accepting PRs for Now 1.0 into this repository so that we may focus on moving our customers onto Now 2.0. 

If you'd like to take a stab at moving it over to Now 2.0, we'd love to take a look at a PR for that!

**Comment by antony** [comment]
@timothyis I'm looking into it. I haven't had much luck so far, but I'll keep trying.

**Comment by etamity** [comment]
> I've added a ghost v2 example in its absence.
> It's based roughly on the [original v1 example](https://github.com/now-examples/ghost).
> I don't think it would be difficult to make this zeit v2 compatible, but I simply don't know how I'm afraid.
> 
> This repo has two significant differences from the original (aside from being v2 not v1), those are to make ghost more useful on an ephemeral filesystem (end users aren't likely going to be the same users who can manage git and now deployments!):
> 
> 1. Added GCP storage adapter to store assets on Google Cloud Platform
> 2. Added external MySQL database connectivity
> 
> It's important to note that due to a [bug in ghost](https://github.com/TryGhost/Ghost/issues/8795) with `contentPath`, when using it as a node module, it's quite difficult to get a local sqlite database to be writable anyway.

Here is one of the way to override the config.
```js
const { join } = require('path');
const defualtConfig = require('./node_modules/ghost/core/server/config');

const contentPath = join(__dirname, 'content');
defualtConfig.set('paths:contentPath', contentPath);
defualtConfig.set('paths:internalStoragePath', join(contentPath, 'adapters/'));
defualtConfig.set(
  'database:connection:filename',
  join(contentPath, 'data', 'ghost-dev.db')
);

const ghost = require('ghost');
const express = require('express');
const { join } = require('path');

async function bootstrap() {
  const server = express();
  const ghostServer = await ghost();
  server.use('/', ghostServer.rootApp);
  ghostServer.start(server);
  return server;
}

```

**Comment by rauchg** [comment]
I think the Ghost example should be similar to how https://wordpress5.now.sh/ works (in that case it's hosted mysql + external uploads)

**Pull request closed without merging**
