### PR TITLE
Add Probot Example

### LINKED ISSUE #175: Probot Example
I thought it would be just `src: index.js` which index `module.exports` a function that gets a Probot instance.

But it's not exactly that way. I also switched to `src: package.json` where I have `now-start` which runs the probot, but seems to not work.

### PR DESCRIPTION
**Pull request by tunnckoCore**
try to resolve #175 

So, any ideas?

### CODE REVIEW

**Comment by rauchg** [comment]
`@node/node-server` should target the file that starts the server. Can you start probot in userspace? This will make booting up much faster

**Comment by tunnckoCore** [comment]
> @node/node-server should target the file that starts the server.

That's okey, but then how we will pass the workaround that we need?

Currently we need this

```json
{
  "now-start": "PRIVATE_KEY=$(echo $PRIVATE_KEY | base64 -d) yarn start",
  "start": "probot run ./index.js",
}
```

Hm, I have an idea.

**Comment by tunnckoCore** [comment]
> Can you start Probot in userspace?

What do you mean? As a builder?

**Comment by tunnckoCore** [comment]
With that, and still fails. Returns `504`.

https://probot-now-v2-30b8b67ce.now.sh/

**Comment by timothyis** [comment]
@tunnckoCore Hi! Did you have a chance to finish what you were working on?

**Comment by timothyis** [comment]
Hi, @tunnckoCore. I'm going to close this PR for now until you can get a working Now 2.0 example working if you'd like to work on it more. Probot is definitely something we're interested in showing an example for so we'd be grateful. 

I may take a stab at this soon!

**Comment by tunnckoCore** [comment]
Oh sure, please assign me for a reminder :)

**Pull request closed without merging**
