### PR TITLE
Add Sanity.io example

### PR DESCRIPTION
**Pull request by rexxars**
This adds an example of building a Sanity.io content studio and deploying it with Now.

### CODE REVIEW

**Comment by paulogdm** [comment]
Hey @rexxars , just don't worry about the TS tests. We will release a fix soon! https://github.com/zeit/ncc/pull/244

**Comment by rexxars** [comment]
Let me know if there is anything here that needs fixing!

**Comment by timothyis** [comment]
Hi @rexxars! I'll check why the deployment failed and get this fixed so we can merge this in 🙏

**Comment by msweeneydev** [comment]
Hey @rexxars, thank you again for opening this PR, apologies about the delay in action. All our examples have been moved to the [zeit/now](https://github.com/zeit/now/tree/master/examples) repository. I will reach out to you soon to get this back in motion in the new location.

**Pull request closed without merging**
