### PR TITLE
Demonstrate @now/go import issue

### PR DESCRIPTION
**Pull request by mxstbr**
When trying to import from a parent directory in the module, the `@now/go` builder throws an error "cannot load module/local: cannot find module providing package module/local".

In the `go-image-to-ascii` examples case, I moved the route to `routes/index.go` and tried to import the same local module as before, `image-to-ascii/ui`. This fails with said error. How can I work around that?

### CODE REVIEW

**Comment by styfle** [comment]
Hi @mxstbr 

Thanks for reporting this bug! The latest canary release should fix this.

Please change your `now.json` file to use `@now/go@canary` to try it out.

**Comment by timothyis** [comment]
Hi @mxstbr, did you test out with @canary?

**Comment by styfle** [comment]
The fix is available in Stable `@now/go`

**Comment by msweeneydev** [comment]
Hey @mxstbr, is this fixed for you in the latest stable?

**Comment by mxstbr** [comment]
Hey sorry, am not using `@now/go` anymore, so I cannot confirm!

**Pull request closed without merging**
