### PR TITLE
Add Ember.js deployment example

### LINKED ISSUE #226: ember deploy example
In your website there is an example of an ember app deployment, but I could not find it here.

### PR DESCRIPTION
**Pull request by ynnoj**
Fixes #226 ✅

### CODE REVIEW

**Comment by timothyis** [comment]
Amazing, thank you @ynnoj! 

That's a lot of code for a Hello World example 😅 Is that standard in the Ember world? 

We are currently looking into more concrete examples, instead of Hello World examples. I'm happy to take this and expand upon it unless you'd like to make it more of a real-world basic example?

**Comment by ynnoj** [comment]
> That's a lot of code for a Hello World example 😅 Is that standard in the Ember world?

😆 this is a default project blueprint from `ember-cli`. It's probably a little overkill for this example, I'll trim it down ✂️ 

> We are currently looking into more concrete examples, instead of Hello World examples. I'm happy to take this and expand upon it unless you'd like to make it more of a real-world basic example?

Sure! What did you have in mind?

**Comment by timothyis** [comment]
That is a good question @ynnoj! I've been speaking to @unicodeveloper internally and I believe the best thing we could do is create an API and template for you to use in ember so that we can start making all examples uniform and concrete.

I'll let you know shortly what we decide on!

**Comment by timothyis** [comment]
Hi @ynnoj! Apologies for the delay, but we've finally settled on what we'd like to use a base example: https://github.com/zeit/now-examples/tree/master/static

This static example is there as a base for what custom examples should look like. If you'd like to work on an Ember.js app based on this, I'd love to see it!

_However_, it has recently been brought up that some users may want a Now-ready application, for technologies such as Ember, as if they were fresh from the ember-cli, or whichever CLI the application came from.

In this case, what do you think about renaming the directory `ember-cli` and creating another for `ember` based on the static template?

**Comment by jmonster** [comment]
A note from a new Zeit Now user -- the README in this PR was all I needed to figure out how to deploy my own ember-cli app to and I'm very grateful that this PR exists to have demonstrated it. I don't think there is much value in providing a full example since it 1) is easily generated with the ember cli and 2) the codebase proposed here (..any codebase proposed here..) is going to become rapidly out of date. Ember moves fast.

**Comment by rauchg** [comment]
Thanks @jmonster – feedback like this is tremendously useful. Let us know if you'd like to join our education channel on Slack. We're constantly looking for ways to make Now better to the Ember ecosystem

**Comment by ynnoj** [comment]
@rauchg I'd be interested in helping out for sure.

**Comment by timothyis** [comment]
@ynnoj Feel free to email me at timothy@zeit.co and I'll invite you!

**Comment by ynnoj** [comment]
@timothyis Will do!

In the meantime, how can we move forward with this PR?

**Comment by msweeneydev** [comment]
Hello @ynnoj, thanks again for contributing here. As you may have seen, we've added an Ember example very recently when we simplified the list - it also requires zero configuration!

As a result, I'm going to close this pull request, thank you for taking the time to submit it though, it really is appreciated and was very useful in getting the current one in place.

**Pull request closed without merging**
