### PR TITLE
Added `create-nuxt-app` to now-examples

### PR DESCRIPTION
**Pull request by Developerayo**
Added `create-nuxt-app` to now-examples based on suggestion. (https://github.com/zeit/docs/pull/560#discussion_r268030608)
@timothyis

### CODE REVIEW

**Comment by timothyis** [comment]
Hi @Developerayo. Could you add this directory to the root `now.json` file so we can see if it deploys okay? Thanks 🙏 

Also, as for the readme, would you mind following the format of the Express example: https://github.com/zeit/now-examples/tree/master/express

We will link to your guide after.

**Comment by Developerayo** [comment]
Alright

**Comment by Developerayo** [comment]
https://github.com/zeit/now-examples/pull/328

**Comment by timothyis** [comment]
@Developerayo to re-iterate my question to you on Slack, does #328 replace this PR?

**Comment by Developerayo** [comment]
Yes, it does!

**Comment by msweeneydev** [comment]
Closing in favour of #328

**Pull request closed without merging**
