### PR TITLE
Add create-elm-app

### PR DESCRIPTION
**Pull request by olpeh**
Adds an example Elm application that could be used as a template for Elm applications

Available at https://create-elm-app-v2.now.sh/

### CODE REVIEW

**Comment by olpeh** [comment]
Please inform me if there is something I can do to help get this published.

**Comment by timothyis** [comment]
Hi @olpeh. Sorry for the delay here. The @zeit/docs team will be getting to this very soon.

**Comment by timothyis** [comment]
Hi @olpeh! Thank you so much for this submission. 

One topic before we go ahead with this: would you be interested in making this example a little more thorough? For example, following the static example (https://github.com/zeit/now-examples/tree/master/static) to make a simple site that pulls in 5 Hacker News posts but extending it based on how Elm works?

Let me know your thoughts 😄

**Comment by olpeh** [comment]
Hey. My idea with this was that this would be identical to what create-elm-app outputs in order to make it easy to upgrade the example whenever create-elm-app gets updates.

Additionally, I think it would be in line with the create-react-app example: https://cra-v2.now.sh/

We could probably create a more advanced Elm example application later.

**Comment by timothyis** [comment]
That's a very good point @olpeh. When looking for `create-[something]-app`, users are probably looking for the base. We should definitely create a more advanced Elm app like mention before in that case. Is this something you'd like to contribute?

**Comment by olpeh** [comment]
@timothyis I'm definitely interested in contributing to a more advanced Elm example whenever I have time.

**Comment by timothyis** [comment]
@olpeh, would you mind just adding this as a build to the root `now.json` file so we can confirm that the check passes? Once that's done, we can merge this in 🙏

**Comment by olpeh** [comment]
I tried, seems like the build for that commit failed. What went wrong @timothyis ?

**Comment by timothyis** [comment]
Apologies for that @olpeh, for security, when there are changes to the `now.json` file we require authorisation to deploy. Thanks for adding though!

**Comment by olpeh** [comment]
Any plans to publish this at some point?

**Pull request merged**
