### PR TITLE
Add revamped examples-api

### PR DESCRIPTION
**Pull request by amio**
This PR added examples-api to @zeit/now-examples repo.

### Motivation

Previously our examples-api (https://now-example-files.zeit.sh) lives in [a standalone repo](https://github.com/zeit/api-examples), it fetch this repo from GitHub, parse and pack files to serve api requests.

Even with aggressive cache configuration, it still suffered from connection to GitHub occasionally, it cannot lives on its own. This is the key reason for this PR, but not only that.

### Benefits

- No longer rely on connection to GitHub, less failure 💪
- No longer download & pack on the fly, all response is pre-generated files 🚀
- Always sync with `zeit/now-examples` ✅
- Simpler code base (195 => 45 sloc) 🎉

### How it works

- Generate static response files with `build-api.js`, to `dist` dir
- Auto deployed with build config `{ "src": "package.json", "@now/static-build" }`

### Endpoints

```
 *     Get a list of example names in zeit/now-examples
 *     /_api/list.json
 *
 *     Get detailed list of all examples
 *     /_api/manifest.json
 *
 *     Download example files by name (e.g. "apollo")
 *     /_api/download/apollo.tar.gz
```

### Notes

- `/list-all.json` is `/_api/manifest.json` now, since it's just a copy job, in the same repo, I wish to keep the naming consistent @quietshu 
- `/info.json?repo=zeit/api-examples` seems more general, it can be a standalone service, what do you think? @quietshu 
- This PR also add an auto alias `https://now-examples.zeit.sh`.

### CODE REVIEW

**Comment by quietshu** [comment]
Agree on 1), we need to update front to avoid down time. For 2), yes we can move it out of here. 👍

**Comment by amio** [comment]
@leo For the implementation detail, @quietshu can do that.

@quietshu Api endpoints are listed here:
https://now-examples-git-add-examples-api.zeit.sh/_api/

**Comment by quietshu** [comment]
@amio Sure I will take this. @leo It also needs some updates in `front`, let's label it as WIP.

**Comment by msweeneydev** [comment]
Closing in favour of #466 due to the large diff created from the zero configuration merge.

**Pull request closed without merging**
