### PR TITLE
Add go middleware example

### PR DESCRIPTION
**Pull request by bluebeel**
I updated the example according to my [**PR#3**](https://github.com/zeit/now-builders/pull/3) in the repo **[now-builders](https://github.com/zeit/now-builders)** where I added the possibility to put middlewares.

To test the example you must use my package ([**@bluebeel/go**](https://www.npmjs.com/package/@bluebeel/go)) in the build of the file _now.json_ for the moment the time that the PR on the other repo is accepted.

### CODE REVIEW

**Comment by bluebeel** [comment]
I don't know why the now bot integration fail :/
I could deploy on my machine.
https://go-i2nidmtpy.now.sh/ and the [logs](https://zeit.co/bluebeel/go/i2nidmtpy/logs)

**Comment by TejasQ** [comment]
@bluebeel are you still interested in this PR? I'd gladly collaborate with you and help you get it up if you'd like. 😄

**Comment by bluebeel** [comment]
Hello,
I don't think my pr is still valid with all the improvement made on the official go builder.
We should start a new pr with the new go builder

**Comment by timothyis** [comment]
Thanks for the contribution @bluebeel. As you said, we need to look into this with the latest @now/go Builder. We'll try to use this as a base!

Please feel free to contribute a new PR if you feel you can provide a great example of how it should be done 🙏

**Pull request closed without merging**
