### PR TITLE
Add umijs static example

### PR DESCRIPTION
**Pull request by lemol**
This adds a basic (but extensible) static umijs app bootstraped following the umi guide on https://umijs.org/guide/create-umi-app.html.

Live deploy: https://umijs-static.lemol.now.sh/

### CODE REVIEW

**Comment by msweeneydev** [comment]
Hey @lemol! Thank you for this contribution, it looks great!

Could you change the README file to follow a pattern closer to the one found in the [Node.js Example](https://github.com/zeit/now-examples/tree/master/nodejs) please?

Other than that, everything looks good to me.

**Comment by lemol** [comment]
@msweeneydev thank you for reviewing.
The README file was created following the pattern of create-react-app, nextjs or nuxt. I opted this pattern because umi is comparable to these frameworks.
What is the reason to follow the nodejs example?

**Comment by ycjcl868** [comment]
@lemol  thanks for your pr about umi, umijs can support ssr and prerender, maybe you can change into prerender demo.  

- https://github.com/umijs/plugins/tree/master/packages/%40umijs/plugin-prerender
- https://github.com/umijs/umi-example-ssr

**Comment by ycjcl868** [comment]
@lemol  thanks for your pr about umi, umijs can support ssr and prerender, maybe you can change into prerender demo.  

- https://github.com/umijs/plugins/tree/master/packages/%40umijs/plugin-prerender
- https://github.com/umijs/umi-example-ssr

**Comment by leo** [comment]
Thanks for this wonderful PR!

May I ask how it differs from our already existing example [here](https://github.com/zeit/now-examples/tree/master/umijs)? Both seem to be static.

**Comment by ycjcl868** [comment]
I think it's difference(Pre rendered with server) with the example(CSR)

**Comment by leo** [comment]
I see!

However, I recommend that we only keep a single example per framework (+ one for adding a function to it). In turn, we need to decide whether the current one or yours is better.

Personally, I would opt for the one that UmiJS provides out of the box, as a boilerplate.

Thanks so much for sharing the context with us! I didn't know there were two ways to handle a UmiJS project.

cc @msweeneydev

**Comment by msweeneydev** [comment]
Hey @lemol, thanks again for submitting this PR. After considering it further, I agree with what @leo is saying in that it might be confusing for users to see multiple examples per framework. The only time we do that currently is to highlight the use of serverless functions.

As a result, I am closing this PR. Thanks again for taking the time to contribute, it is much appreciated.

**Pull request closed without merging**
