### PR TITLE
add sasazushi to sushi types 🍣🎍😋

### PR DESCRIPTION
**Pull request by coetry**
sourced from here: https://gurunavi.com/en/japanfoodie/2017/05/types-of-sushi.html?__ngt__=TT0f17bf98300aac1e4aee4aV1-BYrleACRr5uj8sGj0CX

### CODE REVIEW

**Comment by rauchg** [comment]
Let's host the static assets on the Now deployment itself. At some point in the future, those images will 404 :P

**Comment by coetry** [comment]
@rauchg oh right! will fix that

**Comment by TejasQ** [comment]
@coetry what's up with your deployment? Can I help fix it?

**Comment by coetry** [comment]
for some reason it looks like python is failing, but I haven't touched it

**Comment by TejasQ** [comment]
@coetry gonna close and reopen this to trigger a rebuild of Now.

**Pull request merged**
