### PR TITLE
Add Flaskex for CockroachDB to Now Examples

### PR DESCRIPTION
**Pull request by nstewart**
PR to add a CockroachDB example to Zeit. This was forked from the Flaskex-postgres example and updated to use the CockroachDB-specific driver.

### CODE REVIEW

**Comment by timothyis** [comment]
Hi @nstewart, thanks for the submission, and apologies for the late response here!

Would you be able to share a deployment link for this example? We'd love to get this in, depending on some review criteria based on the deployment.

**Comment by nstewart** [comment]
Thanks — will try to update this over the weekend

Nate Stewart 
(810) 814-3581 | LinkedIn ( http://www.linkedin.com/in/natepstewart )

**Comment by nstewart** [comment]
Here's a deployment link: https://zeit.co/nstewart/flaskex-cockroachdb/o8p085tql

**Comment by rauchg** [comment]
@nstewart mind sharing the deployment URL (*.now.sh) vs the deployment inspector URL?

**Comment by rauchg** [comment]
Thanks for taking the time btw!

**Comment by nstewart** [comment]
Oops -- here you go: https://flaskex-cockroachdb-o8p085tql.now.sh/

**Comment by msweeneydev** [comment]
Hey @nstewart, thank you for submitting this example, my apologies that action wasn't taken sooner. We're now moving all our examples over to the [zeit/now](https://github.com/zeit/now/tree/master/examples) repository and would love to look at putting out a guide showing CockroachDB on ZEIT Now ASAP. I'll be reaching out soon to make this happen alongside an example.

**Pull request closed without merging**
